Fix readme
rackspace-infrastructure-automation/aws-terraform-vpc_basenetwork pull request #15
Opened 2018-11-26 14:47 UTC by mjcmtb

Updating based on external PR https://github.com/rackspace-infrastructure-automation/aws-terraform-vpc_basenetwork/pull/14

2018-11-26 16:31 UTC, twistedgrim submitted a review, later dismissed
LGTM

2018-11-26 16:51 UTC, johnctitus requested changes
We should update the main.tf header so future updates via TFDocs don't override this change.

2018-11-27 16:16 UTC, twistedgrim commented
added the fix to the main.tf's header

2018-11-27 16:17 UTC, twistedgrim approved these changes

2018-11-27 16:17 UTC, johnctitus approved these changes

2018-11-27 16:27 UTC, merged